= Информация по использованию Swagger
Kasta Group LLC <info@tbt-post.net>
1.0.0, 2020-01-01: Public API
:toc: right
:toclevels: 4
{empty}

==== Открытие редактора
Необходимо перейти в онлайн редактор https://editor.swagger.io/[swagger]


==== Импорт настроек редактора
* В верхнем левом углу приложения, кликните на кнопку *File*
* B контекстном меню  выберите опцию *Import File* 
* Bыберите необходимый для просмотра файл с разширением *yaml*, например *_api.yaml_*


==== Использование

====== Авторизация

Для выполения api вызовов в приложении необходима авторизация.
Для авторизации, в правой части приложения, кликните кнопку *Authorize*, введите логин и пароль тестового пользователя и нажмите *Authorize* еще раз.

NOTE: авторизация выполяеться по BasicAuth

====== Выполнение запросов

- Выберите необходимы запрос для проверки.
- Нажмите кнопку *Try it out* внутри описания запроса и затем введите необходимые параметры для запроса
- Отправьте запрос по кнопке *Execute*.

NOTE: После отправки запроса вы увидите сам запрос и ответ на него в поле *Responses*

====== Коды ответов

- Если вы получили код ответа Code 200 – .
- Если вы получили код ответа Code 403 'message': 'Forbidden' – у вас нету прав доступа к серверу по причине не корректной авторизации. Необходимо перепроверить данные и авторизироваться еще раз.
- Если вы получили код ответа Code 401 'message': 'Authorization Required' – вышло время сессии. Необходимо повторная авторизация.
- Остальные возможные не типичные ошибки описаны под каждым запросом.



.Responce codes
[cols="1,3",width="70",options="header,footer"]
|====================
|Код ошибки| Информация
|200|Запрос был успешно выполнен 
|401|У вас нету прав доступа к серверу по причине не корректной авторизации или вышло время сессии. Необходимо перепроверить данные и авторизироваться еще раз.
|403|Запрос выполнен, но у вас нет прав для просмотра содержимого
|====================

NOTE: Основные используемые коды ответом описанны в документе https://github.com/tbt-post/tbtapi-docs/blob/master/adoc/api.adoc[api]
