= TbT Classifier
MelKori <mieldo@gmail.com>
1.3.2, 2018-11-01 (1:1.3.2): API Classifier
:toc: right
:toclevels: 4
{empty}

== Классы отправлений

Структура кода

    <Originator type>.<Payment conditions>.<Returnability>.<Return Payer>.<Insurance>

.Originator Type
[horizontal]
A:: Отправление агентской системы (Agent's parcel)
I:: Собственное отправление платформы (Internal)
U:: Отправление пользователь-курьер (User's parcel)

.Payment conditions
[horizontal]
COD:: наложенный платеж (cash on delivery)
PRP:: предоплаченный заказ (prepaid)
VCD:: наложенный платеж с балланса в системе (virtual coins delivery)

.Returnability
[horizontal]
NR:: невозвратный (no returns)
SA:: возможна частичная выдача (split available)
RA:: возвратный (return available)

.Return Payer
[horizontal]
SP:: отправитель платит (sender pays)
RP:: получатель платит (receiver pays)
BP:: обе стороны платят (both pay)
NA:: не применимо (not available)

.Insurance
[horizontal]
S000:: стандартные уловия страхования, размер покрытия 10-х долях %
C000:: специальный условия страхования, размер покрытия 10-х долях %

.Пример
    A.COD.NR.NA.S000

== Типы отправлений

.Типы
[width="80%",cols=3,options="header"]
|====================
| #
| Название типа
| Описание типа

| 0
| undef
| Без типа

| 1
| papers
| Документы и т.п.

| 2
| fragile
| Хрупкое, ломкое, бьющееся

| 3
| goods
| Вещи, товары потребления

| 4
| foods
| Пищевые продукты

| 5
| chemicals
| Хим. товары

| 6
| special
| Товары, требующие особого внимания

| 7
| hazard
| Опасный груз
|====================

== Маркировка

Для маркировки успользуется от 1 до 2 символов латинского алфавита.
Маркировка предназначена для фиксации операционного процесса, не влияющего
прямо или косвенно на классификацию или типизацию самого отправления.

.Маркировка
[width="80%",cols=2,options="header"]
|====================
| Символ
| Описание

| "O"
| Отмены (произв. PO0099)

| "Z"
| Отказы (произв. PO0098)

| "R"
| Возвраты (произв. PO0097)

| "P"
| Проблемные (произв. PO0096)

| "B"
| Поврежденные (произв. PO0095)
|====================

== Типы доставки

.Delivery Type
[horizontal]
W2W:: Отправление отделение - отделение
W2D:: Отправление отделение - двери (курьерская доставка)
D2W:: Отправление двери - отделение (курьерская доставка)
D2D:: Отправления двери - двери (курьерская доставка x2)
