= TbT FMS Terminals API (v0/simple)

Інтерфейс (протокол) електронної взаємодії систем обліку платформи та платіжного серверу Фінансової установи

== Вимоги до інтерфейсу провайдера

NOTE: Список IP для виконання запитів обговорюється на етапі підключення провайдера до платформи.

. Інтерфейс повинен приймати запити за протоколом HTTP(S) __виключно__
. Інтерфейс повинен обробляти параметри, що передаються системою методом GET
. Інтерфейс повинен формувати відповідь системі в форматі XML в кодуванні windows-1251
. Інтерфейс повинен переносити багатопотокову комунікацію до 10-15 одночасних з’єднань.
. Авторизація відбувається за допомогою Basic Auth, у якому login — це merchantid

== Основні принципи роботи інтерфейсу

. Всі запити до платформи містять наступні змінні: `cmd` та `merchant`.
. Приймання платежів може відбуватися в два етапи: перевірка облікового запису абонента і проведення платежу. Перевірка облікового запису не призводить до будь-яких фінансових наслідків.
. Провайдер ідентифікує свого абонента за унікальним ідентифікатором (номер особового рахунку, телефону, логін і т.д.). Ідентифікатор абонента передається фінансовою системою в змінній account – строчка, яка містить букви, цифри і спеціальні символи, довжиною до 200 символів. У випадку якщо запит на перевірку ідентифікатора завершився помилкою, то платформа повертає код помилки.
. Кожний платіж в платформі має унікальний ідентифікатор (ціле число більше за 0), який передається провайдером або фінансовою системою в змінній id. 
. У відповіді на запит поповнення особового рахунку і перевірки платежу платформа передає час закінчення транзакції (час зарахування коштів абоненту) в форматі РРРР-ММ-ДД ГГ:ХХ:СС. Цей час буде використано для звіряння з фінансовою системою і формування звітних документів.
. В базі даних платформи не повинно міститися двох успішно проведених платежів з однаковими номерами id. Якщо система провайдера повторно надсилає запит з  id, що вже існує в базі платформи, то платформа поверне результат обробки минулого запиту.
. Сума платежу приймається від абонента і передається платформі в гривнях у змінній sum (може бути дрібним числом з точністю до сотих, в якості роздільника використовується «.» крапка), наприклад: 20.05 гривень.
. У випадку якщо запит на проведення платежу завершається помилкою, то платформа повертає код помилки у відповідності до таблиці 1. Всі помилки мають признак фатальності. Для фінансової системи фатальна помилка означає, що повторна відправка запиту з такими же параметрами, призведе до 100% повторення тієї ж помилки – відповідно, платформа припиняє обробку клієнтського запиту і відміняє платіж. Нефатальна помилка  означає для системи, що повторення запиту з тими ж параметрами через деякий проміжок часу, можливо, призведе до успіху. Система буде повторювати запити, які завершуються нефатальною помилкою, постійно з інтервалом 5 хвилин, доки операція не завершиться успіхом або фатальною помилкою. Відсутність зв’язку з сервером провайдера, відсутність елемента result, некоректний XML, сторінка «Service temporarily unavailable» і т.д. – є нефатальними помилками.
. Фінансова система повинна реалізувати перевірку платежу за унікальним номером ідентифікатора id.

== Приклад запитів до платформи

Далі наводиться приклад, у якому:

NOTE: платіжне програмне забезпечення платформи payment/terminal розташовується за адресою https://sandbox-api.tbt-post.net

=== Перевірка особового рахунку

Приклад запиту на перевірку особового рахунку абонента в білінговій системі платформи

Фінансова система генерує запит наступного вигляду:

    https://sandbox-api.tbt-post.net/payment/terminal?cmd=verify&merchantid=p_provider&account=54785216&id_project=tabata-05

Строчка запиту містить наступні змінні:

[horizontal]
cmd=verify::			запит на перевірку облікового запису абонента
merchantid=p_provider::	ідентифікатор фінансової системи
account=380663983399::	особовий рахунок абонента
id_project=tabata-05::  використовується ідентифікаціі доданку та його версії, що призначені для специфічної обробки послуги.

.Додатково
[horizontal]
office=<provider-office-id>:: опціональний параметр. ідентифікатор відділення провайдера для фільтрації реєстру замовлень клієнта в його межах

Відповідь платформи повинна виглядати так:

[source, xml]
----
<?xml version="1.0" encoding="windows-1251"?>
<response>
	<result>21</result>
    <text></text>
	<comment>Orders exists</comment>
	<account>380663983399</account>
	<grouped_list>true</grouped_list>
	<orders>
	        <order>
	            <provider_ident>Kasta</provider_ident>
	            <provider_id_s>1097</provider_id_s>
	            <sum>10.00</sum>
	            <id>M1MP2K7</id>
	            <note>Поповнення по замовленню M1MP2K7</note>
	            <ucode>5600991221001</ucode>
	            <type>2</type>
	            <subtype>0</subtype>
	            <identity>1234567</identity>
	        </order>
	 </orders>
</response>
----

Повернення `result=21` на запит `verify` свідчить про те, що білінгова система платформи працює в штатному режимі, особовий рахунок абонента з відповідним номером існує і може бути поповненим.

У разі наявності реєстру сплат — вони вказуються у вкладеному списку orders, кожен елемент order якого є відокремленою сплатою за окреме замовлення/окремими реквізитами.

Додатковий глобальний параметр `grouped_list` у разі його виставлення у значення `true` свідчить про необхідність групування реєстру замовлень за параметром `id`.

Опціональний елемент `note` містить текстовий опис призначення платежу за замовленням.

Опціональні параметри `provider_ident` та `type` призначені для відображення відповідного ідентифікатора отримувача коштів (за наявності та потреби) та типу фінансової операциї (__0__ — товари, __1__ — послуги, __2__ — транзитне перерахування на іншу фінансову установу) відповідно.

*У разі використання типу (type) __2__ (тобто транзитного перерахування)* елемент `provider_id_s` містить ідентифікатор іншої фінансової установи у системі, а елементи `subtype` та `identity` використовуються для визначення типу платежу у кінцевій фінансовій установі та ідентифікації в ній кінцевого отримувача коштів відповідно. Вказанні значення необхідно передавати при виконанні комманди `pay`

Елемент `ucode` є обов’язковим, він містить унікальний код одиниці товару чи послуги у контексті замовлення ідентифікованого елементом `id` того ж рівня. 

В необов’язковому параметрі `text` передається інформація, яка буде відображена на кінцевому обладнанні або ПО клієнту (ПІБ, баланс тощо).

=== Поповнення особового рахунку

Приклад запиту на поповнення особового рахунку

Фінансова система генерує запит наступного вигляду:

    https://sandbox-api.tbt-post.net/payment/terminal?cmd=pay&merchantid=p_provider&account=54785216&sum=12.74&id=6412547&id_project=tabata-05&type=2&payment_type=cash&ucode=5600991221001&subtype=0&identity=1234567

Строчка запиту містить наступні змінні:

[horizontal]
cmd=pay::			    запит на проведення платежу
merchantid=p_provider:: ідентифікатор фінансової системи
account=54785216::		праметр `id` у відповідь на `cmd=verify`
sum=12.74::		        сума поповнення
id=6412547::			унікальний ідентифікатор платежу в фінансовій системі
id_project=tabata-05::  використовується ідентифікаціі доданку та його
версії, що призначені для специфічної обробки послуги.
terminal_id=<id>::  опціональний параметр. Id терміналу оплати.
payment_type=cash::     необов’язковий параметр, що ідентийікує тип розразунку (`cash` — замовчування для терміналів самообслуговування), де: `cas`h — це розрахунок готівкою, `card` — розрахунок карткою (у разі, якщо термінал обладнано відповідним пристроєм), `emoney` - розрахунок електронними грошима з гаманця платника (у разі доступності функціоналу)
type=2::                необов’язковий параметр, що ідентифікує тип платежу, де: __0__ — товари, __1__ — полуги, __2__ — транзитне перерахування на іншу фінансову установу. Якщо не передається, то за замовчуванням буде дорівнювати значенню __-1__ (`тип платежу не визначено`)
ucode=5600991221001::   унікальний код одиниці товару у вкладенні
ubtype=0::              ідентифікатор типу платежу у кінцевій фінансовій установі
identity=1234567::		ідентфікатор кінцевого отримувача коштів у іншій фінансовій установі


Відповідь платформи повинна виглядати так:

[source, xml]
----
<?xml version="1.0" encoding=" windows-1251"?>
<response>
	<result>27</result>
	<id>6412547</id>
	<provider_id>25478</provider_id>
	<provider_time>2007-11-25 14:52:07</provider_time>
	<provider_id_s></provider_id_s>
	<comment>Transaction complete</comment>
</response>
----

Повернення `result=27` на запит `pay` свідчить про те, що білінгова система платформи однозначно поповнила баланс абоненту на відповідну суму. 

Фінансова система повністю завершає обробку даної транзакції.
В необов’язковому параметрі `provider_id_s` передається код, виданий фінансовою системою, при необхідності перерахування коштів на кількох одержувачів

=== Перевірка платежу

Приклад запиту на перевірку платежу

Фінансова система генерує запит наступного вигляду:,

    https://sandbox-api.tbt-post.net/payment/terminal?cmd=check&merchantid=p_provider&id_project=tabata-05

Строчка запиту містить наступні змінні:

[horizontal]
cmd=check::			    запит на перевірку платежу
merchantid=p_provider:: ідентифікатор фінансової компанії	
id=6412547:: 			унікальний ідентифікатор платежу в системі p_provider
id_project=tabata-05::  використовується ідентифікаціі доданку та його версії, що призначені для специфічної обробки послуги.

Відповідь платформи повинна виглядати так:

[source, xml]
----
<?xml version="1.0" encoding=" windows-1251"?>
<response>
	<result>27</result>
	<id>6412547</id>
	<provider_id>25478</provider_id>
	<provider_time>2007-11-25 14:52:07</provider_time>
	<provider_id_s></provider_id_s>
	<comment>Transaction complete</comment>
</response>
----

Повернення `result=27` на запит `check` свідчить про те, що білінгова система платформи однозначно поповнила баланс абоненту на відповідну суму. Фінансова система повністю завершує обробку даної транзакції.

=== Відміна платежу

Приклад запиту на відміну платежу

Фінансова система генерує запит наступного вигляду:

    https://provider.example.net:5436/get_request.cgi?cmd=cancel&merchantid=p_provider&id=6412547&providerid=25478&account=54785216&sum=12.74&id_project=tabata-05

Строчка запиту містить наступні змінні:

[horizontal]
cmd=cancel::			запит на відміну транзакції
merchantid=p_provider:: ідентифікатор фінансової компанії	
id=6412547::			унікальний ідентифікатор платежу в системі p_provider
providerid=25478::		унікальний ідентифікатор платежу в системі провайдера
account=54785216::		особовий рахунок абонента
sum=12.74::			    сума поповнення
id_project=tabata-05::  використовується ідентифікаціі доданку та його версії, що призначені для специфічної обробки послуги.

Відповідь провайдера повинна виглядати так:

[source, xml]
----
<?xml version="1.0" encoding=" windows-1251"?>
<response>
	<result>80</result>
	<id>6412547</id>
	<provider_id>25478</provider_id>
	<comment>Transaction canceled</comment>
</response>
----

Повернення `result=80` на запит `cancel` свідчить про те, що білінгова система провайдера однозначно відмінила транзакцію, і кошти були списані з рахунку абонента.

В практиці може виникнути необхідність відміни успішної транзакції у випадку помилкового введення абонентом невірного номеру особового рахунку; помилки в наборі особового рахунку касирами стаціонарних терміналів, POS-терміналів або програмних-терміналів, збою програмного забезпечення сторонніх систем, підключених до фінансової системи за XML-протоколом. Відміна транзакції можлива не більш ніж протягом доби (до проведення звіряння платежів).  Рішення про відміну платежів приймаються службою підтримки фінансової системи на власний розсуд. Даний функціонал є опціональним і не є обов’язковим. Рішення про реалізацію можливості відміни платежу приймаються на стороні провайдера.

=== Перевірка поточного балансу

Приклад запит перевірки поточного балансу системи у платформі

Фінансова система генерує запит наступного вигляду:

    https://sandbox-api.tbt-post.net/payment/terminal?cmd=balance&merchantid=p_provider&id=6412547&id_project=tabata-05

Строчка запиту містить наступні змінні:

[horizontal]
cmd=balance::			запит на перевірку поточного балансу системи
merchantid=p_provider:: ідентифікатор p_provider
id_project=tabata-05::  використовується ідентифікаціі доданку та його версії, що призначені для специфічної обробки послуги.

Відповідь провайдера повинна виглядати так:

[source, xml]
----
<?xml version="1.0" encoding=" windows-1251"?>
<response>
	<result>10</result>
	<balance>254.91</balance>
</response>
----

В залежності від застосованої фінансової схеми співпраці з провайдером може виникнути необхідність перевірки поточного балансу системи у платформі. Даний функціонал обов’язковий, якщо співпраця з платформою ведеться за передплатою.

== Щоденне звіряння платежів

В 6:00 за київським часом платформа починає процедуру генерації і розсилання щоденних реєстрів платежів фінансовим системам та провайдерам. Система генерує і відправляє за вказаною адресою електронний реєстр прийнятих платежів за попередній день відповідно до часу платформи. 

Реєстр має наступну структуру:

[source, csv]
----
Total: <кіл-сть платежів>;<загальна сума>
id;ucode;providerid;provider_time;account;sum;payment_type;type;subtype;identity;fee;provider_id_s;order_id
Наприклад:
Total: 3;123.87
458749;458749;12547;2017-11-25 12:45:21;2356;21.87;card;0;;;0.22;1027;KM240Z7
458963;011223;15548;2017-11-25 18:11:37;1457;50;cash;-1;;;0.5;1098;MK0427Z
458977;412342;15558;2017-11-26 16:14:57;1419;52;card;2;1223;11231123;0.52;1598;KS877TR
----

Система включає в реєстр тільки успішно проведені платежі. У випадку якщо в реєстрі містяться розбіжності, то необхідно зв’язатися з відповідальною особою в фінансовій установі для з’ясування ситуації та прийняття рішення.

== Перелік відповідей

При обробці запитів від системи, фінансова система повинна співставити всі помилки, що виникли в його програмному забезпеченні, з приведеним нижче переліком і повертати відповідні коди в елементі `<result>`. Знак `+`` в стовбці `Фатальність` – вказує на те, як система буде інтерпретувати дану помилку. 

[width="75%",frame="topbot",cols="1,^4,^1,options="header,footer"]
|======================
| Код | Опис помилки | Фатальність
| -90 | Інша помилка провайдера | +
| -86 | Відміна платежу неможлива | +
| -49 | Збій білінгової системи | -
| -41 | Приймання платежів для абонента заборонене | +
| -40 | Абонент не знайдений/у абонента відсутні послуги до сплати | +
| -27 | Транзакція не знайдена | +
| -13 | Помилка запиту | -
| -10 | Тимчасова помилка провайдера. Повторіть запит пізніше | -
| 10 | Дію визначено | +
| 21 | Абонент існує | +
| 25 | Платіж прийнятий і знаходиться в черзі на проведення | -
| 27 | Платіж визначено | +
| 80 | Платіж відмінено | +
|======================
